### PR TITLE
Aq 1406 edit modal scope

### PR DESCRIPTION
**Pull request by msakauye**
allow for additional model fields in edit modal. previously just copied title from the model, but we want everything the model has.

---

This change is [Reviewable](https://reviewable.io/reviews/aquicore/angular-dashboard-framework/5)

### CODE REVIEW

**Comment by msakauye** [comment]
@mikedon

**Comment by mikedon** [comment]
Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/templates/material/dashboard-edit.html, line 34 at r2](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5#-KUFXJINqrDk5An-y_6N:-KUFXJINqrDk5An-y_6O:bnug3lx) ([raw file](https://github.com/aquicore/angular-dashboard-framework/blob/fd02a729172c767a552fb08068822ecb316dadbc/src/templates/material/dashboard-edit.html#L34)):_

> ``` HTML
>     </md-dialog-content>
>     <md-dialog-actions layout="row">
>       <md-button type="button" class="primary" ng-click="applyDialog()" ng-bind="translate('ADF_COMMON_CLOSE')">Apply</md-button>
> ```

does "save" make more sense?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5)_

**Comment by msakauye** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/templates/material/dashboard-edit.html, line 34 at r2](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5#-KUFXJINqrDk5An-y_6N:-KUFXh3GwBtLAz05Kkf5:b-qoapzx) ([raw file](https://github.com/aquicore/angular-dashboard-framework/blob/fd02a729172c767a552fb08068822ecb316dadbc/src/templates/material/dashboard-edit.html#L34)):_
<details><summary>

<i>Previously, mikedon (miked) wrote…</i></summary>



> does "save" make more sense?
> </details>
> This just applies the settings to the dashboard the user is currently looking at, but it's not permanent. There's a separate save button for that outside of the modal. I didn't want to use the same wording and make it confusing 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5)_

**Comment by mikedon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/templates/material/dashboard-edit.html, line 34 at r2](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5#-KUFXJINqrDk5An-y_6N:-KUHEL9VZx44mbhX3bpb:b-88rsc1) ([raw file](https://github.com/aquicore/angular-dashboard-framework/blob/fd02a729172c767a552fb08068822ecb316dadbc/src/templates/material/dashboard-edit.html#L34)):_
<details><summary>

<i>Previously, msakauye (Mark) wrote…</i></summary>



> This just applies the settings to the dashboard the user is currently looking at, but it's not permanent. There's a separate save button for that outside of the modal. I didn't want to use the same wording and make it confusing 
> </details>
> FINE.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5)_

**Comment by mikedon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/angular-dashboard-framework/5#-:-KUHEMSN4tsOoR7O5NTd:bnfp4nl)_

**Pull request merged**
